---@class LazyVimOptions
return {
  colorscheme = 'catppuccin',
  icons = {
    misc = {
      dots = '󰇘',
    },
    ft = {
      octo = '',
    },
    treesitter = ' ',
    lsp = '  ',
    null_ls = '󰉼 ',
    dap = {
      Status = ' ',
      Stopped = { '󰁕 ', 'DiagnosticWarn', 'DapStoppedLine' },
      Breakpoint = { ' ' },
      BreakpointCondition = { ' ' },
      BreakpointRejected = { ' ', 'DiagnosticError' },
      LogPoint = { '.>' },
    },
    diagnostics = {
      Error = ' ',
      Warn = ' ',
      Hint = ' ',
      Info = ' ',
    },
    git = {
      added = ' ',
      modified = ' ',
      removed = ' ',
    },
    kinds = {
      Array = ' ',
      Boolean = ' ',
      BreakStatement = '󰙧 ',
      Call = '󰃷 ',
      CaseStatement = '󱃙 ',
      Class = ' ',
      Color = '󰏘 ',
      Constant = '󰏿 ',
      Constructor = ' ',
      ContinueStatement = '→ ',
      Declaration = '󰙠 ',
      Delete = '󰩺 ',
      DoStatement = '󰑖 ',
      Enum = ' ',
      EnumMember = ' ',
      Event = ' ',
      Field = ' ',
      File = ' ',
      Folder = ' ',
      ForStatement = '󰑖 ',
      Function = '󰊕 ',
      Interface = ' ',
      Identifier = '󰀫 ',
      IfStatement = '󰇉 ',
      Keyword = '󰌋 ',
      List = '󰅪 ',
      Log = '󰦪 ',
      Lsp = ' ',
      Macro = '󰁌 ',
      MarkdownH1 = '󰉫 ',
      MarkdownH2 = '󰉬 ',
      MarkdownH3 = '󰉭 ',
      MarkdownH4 = '󰉮 ',
      MarkdownH5 = '󰉯 ',
      MarkdownH6 = '󰉰 ',
      Method = ' ',
      Module = ' ',
      Namespace = ' ',
      Null = ' ',
      Number = '󰎠 ',
      Object = ' ',
      Operator = ' ',
      Package = ' ',
      Pair = '󰅪 ',
      Property = ' ',
      Reference = ' ',
      Regex = ' ',
      Repeat = '󰑖 ',
      Scope = '󰅩 ',
      Snippet = ' ',
      Specifier = '󰦪 ',
      Statement = '󰅩 ',
      String = ' ',
      Struct = ' ',
      SwitchStatement = '󰺟 ',
      Terminal = ' ',
      Text = ' ',
      Type = ' ',
      TypeParameter = '󰆩 ',
      Unit = ' ',
      Value = '󰎠 ',
      Variable = '󰀫 ',
      WhileStatement = '󰑖 ',

      cmdline = ' ',
      codeium = ' ',
      dictionary = ' ',
      calc = ' ',
      sql = ' ',
      dadbod = ' ',
      dap = ' ',
      fish = '󰈺 ',
      git = ' ',
    },
  },
  ---@type table<string, string>
  abbreviations = {
    gh = 'https://github.com/',
    gl = 'https://gitlab.com/',
    dy = 'dynamo',
    tklt = 'takalinhtinh',
  },
}
