local h = require('helpers')

describe('util.root', function()
  local root, dir, cleanup, cwd, restore_spec
  before_each(function()
    dir, cleanup = h.tmpdir()
    cwd = vim.fn.getcwd()
    restore_spec = h.stub(vim.g, 'root_spec', nil)
    h.unload('util.root')
    root = require('util.root')
  end)
  after_each(function()
    restore_spec()
    vim.cmd('silent! %bwipeout!')
    vim.cmd.cd(cwd)
    cleanup()
  end)

  it('finds the nearest directory holding a marker', function()
    h.write(dir .. '/project/.git/HEAD', { 'ref: refs/heads/main' })
    h.write(dir .. '/project/src/deep/file.lua', { '' })
    vim.cmd.edit(dir .. '/project/src/deep/file.lua')
    assert.are.equal(dir .. '/project', root.get())
    assert.are.equal(dir .. '/project', root())
  end)

  it('falls back to the working directory', function()
    vim.cmd.cd(dir)
    h.write(dir .. '/file.txt', { '' })
    vim.cmd.edit(dir .. '/file.txt')
    assert.are.equal(dir, root.get())
  end)

  it('follows vim.g.root_spec', function()
    h.write(dir .. '/a/marker.txt', { '' })
    h.write(dir .. '/a/b/.git/HEAD', { '' })
    h.write(dir .. '/a/b/c.lua', { '' })
    vim.g.root_spec = { 'marker.txt' }
    vim.cmd.edit(dir .. '/a/b/c.lua')
    assert.are.equal(dir .. '/a', root.get())
  end)

  it('caches the root per buffer', function()
    h.write(dir .. '/x/.git/HEAD', { '' })
    h.write(dir .. '/x/y.lua', { '' })
    vim.cmd.edit(dir .. '/x/y.lua')
    local buf = vim.api.nvim_get_current_buf()
    assert.are.equal(dir .. '/x', root.get())
    root.cache[buf] = '/cached'
    assert.are.equal('/cached', root.get())
  end)

  it('gives the git work tree around the root', function()
    h.write(dir .. '/repo/.git/HEAD', { '' })
    h.write(dir .. '/repo/sub/lua/mod.lua', { '' })
    vim.g.root_spec = { 'lua' }
    vim.cmd.edit(dir .. '/repo/sub/lua/mod.lua')
    assert.are.equal(dir .. '/repo/sub', root.get())
    assert.are.equal(dir .. '/repo', root.git())
  end)
end)
